### ISSUE TITLE
IE11 fails with "Const must be initialized" at AbortAlgorithm.ts

### ISSUE THREAD

**Issue by Nunomcg** [oozcitak/dom#2]
IE11 cannot deal with the syntax 
`for (const x of y)`
used in method AbortAlgorithm.abort_signalAbort, among others.

The syntax
`for (let  x of y)`
should be used instead

**Comment by oozcitak** [comment]
I wrote this library with node-js in mind since it doesn't have a DOM implementation as browsers do. Can I ask why you are using this library in the browser? Just trying to understand your use case...

**Comment by Nunomcg** [comment]
I am using **xmlbuilder2**, and some of my customers use IE11. 
xmlbuilder2 depends on @oozcitak/dom

**Comment by Nunomcg** [comment]
would you like me to do a pull request?

**Comment by oozcitak** [comment]
> would you like me to do a pull request?

No, thanks. I am working on creating a browser bundle on the `xmlbuilder2` repo. I may take a few days though.

**Comment by oozcitak** [comment]
I have prepared an `UMD` [bundle](https://github.com/oozcitak/xmlbuilder2/commit/5ff730477e73eeac317f98a279b26b11a26f897b). Now I need to test the major browsers.

**Comment by christopherthurnher** [comment]
I still have the same issue as Nunomcg described in the beginning. IE11 cannot deal with 
`for (const...)`

**Comment by oozcitak** [comment]
Closing this. Tracking on `xmlbuilder2` repo: https://github.com/oozcitak/xmlbuilder2/issues/28

**Comment by oozcitak** [comment]
@christopherthurnher I haven't released it yet. Still have some testing to go.

**Comment by oozcitak** [comment]
Fixed. Please see notes at https://github.com/oozcitak/xmlbuilder2/issues/28#issuecomment-652985549
